/// Flutter icons Premierleaguelogo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Premierleaguelogo
///      fonts:
///       - asset: fonts/Premierleaguelogo.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'Premierleaguelogo';

  static const IconData premierLeagueLogo = IconData(0xe800, fontFamily: _kFontFam,);


  static const _epl = 'Epl';


  static const IconData eplLogo = IconData(0xe800, fontFamily: _epl);


}
